/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import au.com.woolworths.village.sdk.openapi.dto.GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetailStepUp;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail
 */

public class GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CARD_SUFFIX = "cardSuffix";
  @SerializedName(SERIALIZED_NAME_CARD_SUFFIX)
  private String cardSuffix;

  public static final String SERIALIZED_NAME_PROGRAM_NAME = "programName";
  @SerializedName(SERIALIZED_NAME_PROGRAM_NAME)
  private String programName;

  public static final String SERIALIZED_NAME_STEP_UP = "stepUp";
  @SerializedName(SERIALIZED_NAME_STEP_UP)
  private GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetailStepUp stepUp;


  public GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail cardSuffix(String cardSuffix) {
    
    this.cardSuffix = cardSuffix;
    return this;
  }

   /**
   * The suffix (last 4 digits) of the gift card number.
   * @return cardSuffix
  **/
  @ApiModelProperty(example = "2517", required = true, value = "The suffix (last 4 digits) of the gift card number.")

  public String getCardSuffix() {
    return cardSuffix;
  }


  public void setCardSuffix(String cardSuffix) {
    this.cardSuffix = cardSuffix;
  }


  public GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail programName(String programName) {
    
    this.programName = programName;
    return this;
  }

   /**
   * The gift card program name.
   * @return programName
  **/
  @ApiModelProperty(example = "WISH Gift Card", required = true, value = "The gift card program name.")

  public String getProgramName() {
    return programName;
  }


  public void setProgramName(String programName) {
    this.programName = programName;
  }


  public GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail stepUp(GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetailStepUp stepUp) {
    
    this.stepUp = stepUp;
    return this;
  }

   /**
   * Get stepUp
   * @return stepUp
  **/
  @ApiModelProperty(required = true, value = "")

  public GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetailStepUp getStepUp() {
    return stepUp;
  }


  public void setStepUp(GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetailStepUp stepUp) {
    this.stepUp = stepUp;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail getCustomerPaymentInstrumentResultDataPaymentInstrumentDetail = (GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail) o;
    return Objects.equals(this.cardSuffix, getCustomerPaymentInstrumentResultDataPaymentInstrumentDetail.cardSuffix) &&
        Objects.equals(this.programName, getCustomerPaymentInstrumentResultDataPaymentInstrumentDetail.programName) &&
        Objects.equals(this.stepUp, getCustomerPaymentInstrumentResultDataPaymentInstrumentDetail.stepUp);
  }

  @Override
  public int hashCode() {
    return Objects.hash(cardSuffix, programName, stepUp);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GetCustomerPaymentInstrumentResultDataPaymentInstrumentDetail {\n");
    sb.append("    cardSuffix: ").append(toIndentedString(cardSuffix)).append("\n");
    sb.append("    programName: ").append(toIndentedString(programName)).append("\n");
    sb.append("    stepUp: ").append(toIndentedString(stepUp)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

