/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * GiftingProductDetailAllOf
 */

public class GiftingProductDetailAllOf implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_REDEMPTION_INSTRUCTIONS = "redemptionInstructions";
  @SerializedName(SERIALIZED_NAME_REDEMPTION_INSTRUCTIONS)
  private String redemptionInstructions;

  /**
   * The enabled redemption channels
   */
  @JsonAdapter(RedemptionTypeEnum.Adapter.class)
  public enum RedemptionTypeEnum {
    INSTORE("INSTORE"),
    
    ONLINE("ONLINE"),
    
    BOTH("BOTH");

    private String value;

    RedemptionTypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RedemptionTypeEnum fromValue(String value) {
      for (RedemptionTypeEnum b : RedemptionTypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RedemptionTypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RedemptionTypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RedemptionTypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RedemptionTypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_REDEMPTION_TYPE = "redemptionType";
  @SerializedName(SERIALIZED_NAME_REDEMPTION_TYPE)
  private RedemptionTypeEnum redemptionType;

  public static final String SERIALIZED_NAME_TERMS_AND_CONDITIONS = "termsAndConditions";
  @SerializedName(SERIALIZED_NAME_TERMS_AND_CONDITIONS)
  private String termsAndConditions;

  public static final String SERIALIZED_NAME_MIN_VALUE = "minValue";
  @SerializedName(SERIALIZED_NAME_MIN_VALUE)
  private Integer minValue;

  public static final String SERIALIZED_NAME_MAX_VALUE = "maxValue";
  @SerializedName(SERIALIZED_NAME_MAX_VALUE)
  private Integer maxValue;

  public static final String SERIALIZED_NAME_EXPIRY_PERIOD_IN_DAYS = "expiryPeriodInDays";
  @SerializedName(SERIALIZED_NAME_EXPIRY_PERIOD_IN_DAYS)
  private Integer expiryPeriodInDays;

  public static final String SERIALIZED_NAME_EXPIRY_PERIOD_TEXT = "expiryPeriodText";
  @SerializedName(SERIALIZED_NAME_EXPIRY_PERIOD_TEXT)
  private String expiryPeriodText;

  public static final String SERIALIZED_NAME_IS_ACTIVE = "isActive";
  @SerializedName(SERIALIZED_NAME_IS_ACTIVE)
  private Boolean isActive;

  public static final String SERIALIZED_NAME_REDEMPTION_STORES = "redemptionStores";
  @SerializedName(SERIALIZED_NAME_REDEMPTION_STORES)
  private List<String> redemptionStores = null;

  /**
   * Digital or phyiscal availability of the gift card
   */
  @JsonAdapter(AvailabilityEnum.Adapter.class)
  public enum AvailabilityEnum {
    DIGITAL("DIGITAL"),
    
    PHYSICAL("PHYSICAL"),
    
    BOTH("BOTH");

    private String value;

    AvailabilityEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static AvailabilityEnum fromValue(String value) {
      for (AvailabilityEnum b : AvailabilityEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<AvailabilityEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final AvailabilityEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public AvailabilityEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return AvailabilityEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_AVAILABILITY = "availability";
  @SerializedName(SERIALIZED_NAME_AVAILABILITY)
  private AvailabilityEnum availability;

  public static final String SERIALIZED_NAME_DESIGNS = "designs";
  @SerializedName(SERIALIZED_NAME_DESIGNS)
  private List<GiftingProductDesign> designs = new ArrayList<GiftingProductDesign>();


  public GiftingProductDetailAllOf redemptionInstructions(String redemptionInstructions) {
    
    this.redemptionInstructions = redemptionInstructions;
    return this;
  }

   /**
   * Display instruction on where and how to redeem the product
   * @return redemptionInstructions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Display instruction on where and how to redeem the product")

  public String getRedemptionInstructions() {
    return redemptionInstructions;
  }


  public void setRedemptionInstructions(String redemptionInstructions) {
    this.redemptionInstructions = redemptionInstructions;
  }


  public GiftingProductDetailAllOf redemptionType(RedemptionTypeEnum redemptionType) {
    
    this.redemptionType = redemptionType;
    return this;
  }

   /**
   * The enabled redemption channels
   * @return redemptionType
  **/
  @ApiModelProperty(required = true, value = "The enabled redemption channels")

  public RedemptionTypeEnum getRedemptionType() {
    return redemptionType;
  }


  public void setRedemptionType(RedemptionTypeEnum redemptionType) {
    this.redemptionType = redemptionType;
  }


  public GiftingProductDetailAllOf termsAndConditions(String termsAndConditions) {
    
    this.termsAndConditions = termsAndConditions;
    return this;
  }

   /**
   * Terms and conditions text for the gift card product
   * @return termsAndConditions
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Terms and conditions text for the gift card product")

  public String getTermsAndConditions() {
    return termsAndConditions;
  }


  public void setTermsAndConditions(String termsAndConditions) {
    this.termsAndConditions = termsAndConditions;
  }


  public GiftingProductDetailAllOf minValue(Integer minValue) {
    
    this.minValue = minValue;
    return this;
  }

   /**
   * Minimum AUD value gift card able to be purchased for this product
   * @return minValue
  **/
  @ApiModelProperty(required = true, value = "Minimum AUD value gift card able to be purchased for this product")

  public Integer getMinValue() {
    return minValue;
  }


  public void setMinValue(Integer minValue) {
    this.minValue = minValue;
  }


  public GiftingProductDetailAllOf maxValue(Integer maxValue) {
    
    this.maxValue = maxValue;
    return this;
  }

   /**
   * Maximum AUD value gift card able to be purchased for this product
   * @return maxValue
  **/
  @ApiModelProperty(required = true, value = "Maximum AUD value gift card able to be purchased for this product")

  public Integer getMaxValue() {
    return maxValue;
  }


  public void setMaxValue(Integer maxValue) {
    this.maxValue = maxValue;
  }


  public GiftingProductDetailAllOf expiryPeriodInDays(Integer expiryPeriodInDays) {
    
    this.expiryPeriodInDays = expiryPeriodInDays;
    return this;
  }

   /**
   * Expiry period for the gift card product once purchased
   * @return expiryPeriodInDays
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Expiry period for the gift card product once purchased")

  public Integer getExpiryPeriodInDays() {
    return expiryPeriodInDays;
  }


  public void setExpiryPeriodInDays(Integer expiryPeriodInDays) {
    this.expiryPeriodInDays = expiryPeriodInDays;
  }


  public GiftingProductDetailAllOf expiryPeriodText(String expiryPeriodText) {
    
    this.expiryPeriodText = expiryPeriodText;
    return this;
  }

   /**
   * Display text for the expiry period
   * @return expiryPeriodText
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Display text for the expiry period")

  public String getExpiryPeriodText() {
    return expiryPeriodText;
  }


  public void setExpiryPeriodText(String expiryPeriodText) {
    this.expiryPeriodText = expiryPeriodText;
  }


  public GiftingProductDetailAllOf isActive(Boolean isActive) {
    
    this.isActive = isActive;
    return this;
  }

   /**
   * Returns true if the gift card product is active, else false. Only active programs are orderable
   * @return isActive
  **/
  @ApiModelProperty(required = true, value = "Returns true if the gift card product is active, else false. Only active programs are orderable")

  public Boolean getIsActive() {
    return isActive;
  }


  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }


  public GiftingProductDetailAllOf redemptionStores(List<String> redemptionStores) {
    
    this.redemptionStores = redemptionStores;
    return this;
  }

  public GiftingProductDetailAllOf addRedemptionStoresItem(String redemptionStoresItem) {
    if (this.redemptionStores == null) {
      this.redemptionStores = new ArrayList<String>();
    }
    this.redemptionStores.add(redemptionStoresItem);
    return this;
  }

   /**
   * The stores in which the gift card product is able to be redeemed
   * @return redemptionStores
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "The stores in which the gift card product is able to be redeemed")

  public List<String> getRedemptionStores() {
    return redemptionStores;
  }


  public void setRedemptionStores(List<String> redemptionStores) {
    this.redemptionStores = redemptionStores;
  }


  public GiftingProductDetailAllOf availability(AvailabilityEnum availability) {
    
    this.availability = availability;
    return this;
  }

   /**
   * Digital or phyiscal availability of the gift card
   * @return availability
  **/
  @ApiModelProperty(required = true, value = "Digital or phyiscal availability of the gift card")

  public AvailabilityEnum getAvailability() {
    return availability;
  }


  public void setAvailability(AvailabilityEnum availability) {
    this.availability = availability;
  }


  public GiftingProductDetailAllOf designs(List<GiftingProductDesign> designs) {
    
    this.designs = designs;
    return this;
  }

  public GiftingProductDetailAllOf addDesignsItem(GiftingProductDesign designsItem) {
    this.designs.add(designsItem);
    return this;
  }

   /**
   * Array of all alternative designs for the gift card product
   * @return designs
  **/
  @ApiModelProperty(required = true, value = "Array of all alternative designs for the gift card product")

  public List<GiftingProductDesign> getDesigns() {
    return designs;
  }


  public void setDesigns(List<GiftingProductDesign> designs) {
    this.designs = designs;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftingProductDetailAllOf giftingProductDetailAllOf = (GiftingProductDetailAllOf) o;
    return Objects.equals(this.redemptionInstructions, giftingProductDetailAllOf.redemptionInstructions) &&
        Objects.equals(this.redemptionType, giftingProductDetailAllOf.redemptionType) &&
        Objects.equals(this.termsAndConditions, giftingProductDetailAllOf.termsAndConditions) &&
        Objects.equals(this.minValue, giftingProductDetailAllOf.minValue) &&
        Objects.equals(this.maxValue, giftingProductDetailAllOf.maxValue) &&
        Objects.equals(this.expiryPeriodInDays, giftingProductDetailAllOf.expiryPeriodInDays) &&
        Objects.equals(this.expiryPeriodText, giftingProductDetailAllOf.expiryPeriodText) &&
        Objects.equals(this.isActive, giftingProductDetailAllOf.isActive) &&
        Objects.equals(this.redemptionStores, giftingProductDetailAllOf.redemptionStores) &&
        Objects.equals(this.availability, giftingProductDetailAllOf.availability) &&
        Objects.equals(this.designs, giftingProductDetailAllOf.designs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(redemptionInstructions, redemptionType, termsAndConditions, minValue, maxValue, expiryPeriodInDays, expiryPeriodText, isActive, redemptionStores, availability, designs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftingProductDetailAllOf {\n");
    sb.append("    redemptionInstructions: ").append(toIndentedString(redemptionInstructions)).append("\n");
    sb.append("    redemptionType: ").append(toIndentedString(redemptionType)).append("\n");
    sb.append("    termsAndConditions: ").append(toIndentedString(termsAndConditions)).append("\n");
    sb.append("    minValue: ").append(toIndentedString(minValue)).append("\n");
    sb.append("    maxValue: ").append(toIndentedString(maxValue)).append("\n");
    sb.append("    expiryPeriodInDays: ").append(toIndentedString(expiryPeriodInDays)).append("\n");
    sb.append("    expiryPeriodText: ").append(toIndentedString(expiryPeriodText)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    redemptionStores: ").append(toIndentedString(redemptionStores)).append("\n");
    sb.append("    availability: ").append(toIndentedString(availability)).append("\n");
    sb.append("    designs: ").append(toIndentedString(designs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

