/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * For a gifting card, contains the recipient details
 */
@ApiModel(description = "For a gifting card, contains the recipient details")

public class GiftingProductOrderItemRecipientDetails implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_TO_NAME = "toName";
  @SerializedName(SERIALIZED_NAME_TO_NAME)
  private String toName;

  public static final String SERIALIZED_NAME_FROM_NAME = "fromName";
  @SerializedName(SERIALIZED_NAME_FROM_NAME)
  private String fromName;

  public static final String SERIALIZED_NAME_MESSAGE = "message";
  @SerializedName(SERIALIZED_NAME_MESSAGE)
  private String message;

  public static final String SERIALIZED_NAME_IMAGE_URL = "imageUrl";
  @SerializedName(SERIALIZED_NAME_IMAGE_URL)
  private String imageUrl;

  public static final String SERIALIZED_NAME_MOBILE_NUMBER = "mobileNumber";
  @SerializedName(SERIALIZED_NAME_MOBILE_NUMBER)
  private String mobileNumber;


  public GiftingProductOrderItemRecipientDetails toName(String toName) {
    
    this.toName = toName;
    return this;
  }

   /**
   * Name of sender
   * @return toName
  **/
  @ApiModelProperty(required = true, value = "Name of sender")

  public String getToName() {
    return toName;
  }


  public void setToName(String toName) {
    this.toName = toName;
  }


  public GiftingProductOrderItemRecipientDetails fromName(String fromName) {
    
    this.fromName = fromName;
    return this;
  }

   /**
   * Name of recipient
   * @return fromName
  **/
  @ApiModelProperty(required = true, value = "Name of recipient")

  public String getFromName() {
    return fromName;
  }


  public void setFromName(String fromName) {
    this.fromName = fromName;
  }


  public GiftingProductOrderItemRecipientDetails message(String message) {
    
    this.message = message;
    return this;
  }

   /**
   * Optional message to be sent as part of gift card delivery
   * @return message
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional message to be sent as part of gift card delivery")

  public String getMessage() {
    return message;
  }


  public void setMessage(String message) {
    this.message = message;
  }


  public GiftingProductOrderItemRecipientDetails imageUrl(String imageUrl) {
    
    this.imageUrl = imageUrl;
    return this;
  }

   /**
   * Optional image URL for personalisation purposes
   * @return imageUrl
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Optional image URL for personalisation purposes")

  public String getImageUrl() {
    return imageUrl;
  }


  public void setImageUrl(String imageUrl) {
    this.imageUrl = imageUrl;
  }


  public GiftingProductOrderItemRecipientDetails mobileNumber(String mobileNumber) {
    
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * Australian mobile number of recipient. Only SMS delivery method is supported for gifting card
   * @return mobileNumber
  **/
  @ApiModelProperty(required = true, value = "Australian mobile number of recipient. Only SMS delivery method is supported for gifting card")

  public String getMobileNumber() {
    return mobileNumber;
  }


  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GiftingProductOrderItemRecipientDetails giftingProductOrderItemRecipientDetails = (GiftingProductOrderItemRecipientDetails) o;
    return Objects.equals(this.toName, giftingProductOrderItemRecipientDetails.toName) &&
        Objects.equals(this.fromName, giftingProductOrderItemRecipientDetails.fromName) &&
        Objects.equals(this.message, giftingProductOrderItemRecipientDetails.message) &&
        Objects.equals(this.imageUrl, giftingProductOrderItemRecipientDetails.imageUrl) &&
        Objects.equals(this.mobileNumber, giftingProductOrderItemRecipientDetails.mobileNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(toName, fromName, message, imageUrl, mobileNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class GiftingProductOrderItemRecipientDetails {\n");
    sb.append("    toName: ").append(toIndentedString(toName)).append("\n");
    sb.append("    fromName: ").append(toIndentedString(fromName)).append("\n");
    sb.append("    message: ").append(toIndentedString(message)).append("\n");
    sb.append("    imageUrl: ").append(toIndentedString(imageUrl)).append("\n");
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

