/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.math.BigDecimal;
import java.io.Serializable;

/**
 * Results of the gifting quote
 */
@ApiModel(description = "Results of the gifting quote")

public class InlineResponse2002DataOrderItems implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_DESIGN_ID = "designId";
  @SerializedName(SERIALIZED_NAME_DESIGN_ID)
  private String designId;

  public static final String SERIALIZED_NAME_AMOUNT = "amount";
  @SerializedName(SERIALIZED_NAME_AMOUNT)
  private BigDecimal amount;

  public static final String SERIALIZED_NAME_UNIT_PRICE = "unitPrice";
  @SerializedName(SERIALIZED_NAME_UNIT_PRICE)
  private BigDecimal unitPrice;

  public static final String SERIALIZED_NAME_TOTAL_PRICE = "totalPrice";
  @SerializedName(SERIALIZED_NAME_TOTAL_PRICE)
  private BigDecimal totalPrice;

  public static final String SERIALIZED_NAME_QUANTITY = "quantity";
  @SerializedName(SERIALIZED_NAME_QUANTITY)
  private Integer quantity;

  public static final String SERIALIZED_NAME_IS_GIFTING = "isGifting";
  @SerializedName(SERIALIZED_NAME_IS_GIFTING)
  private Boolean isGifting;

  public static final String SERIALIZED_NAME_MOBILE_NUMBER = "mobileNumber";
  @SerializedName(SERIALIZED_NAME_MOBILE_NUMBER)
  private String mobileNumber;


  public InlineResponse2002DataOrderItems designId(String designId) {
    
    this.designId = designId;
    return this;
  }

   /**
   * Unique identifier of the design selected (assumed to be DIGITAL only currently)
   * @return designId
  **/
  @ApiModelProperty(required = true, value = "Unique identifier of the design selected (assumed to be DIGITAL only currently)")

  public String getDesignId() {
    return designId;
  }


  public void setDesignId(String designId) {
    this.designId = designId;
  }


  public InlineResponse2002DataOrderItems amount(BigDecimal amount) {
    
    this.amount = amount;
    return this;
  }

   /**
   * Face value of the gift card
   * @return amount
  **/
  @ApiModelProperty(required = true, value = "Face value of the gift card")

  public BigDecimal getAmount() {
    return amount;
  }


  public void setAmount(BigDecimal amount) {
    this.amount = amount;
  }


  public InlineResponse2002DataOrderItems unitPrice(BigDecimal unitPrice) {
    
    this.unitPrice = unitPrice;
    return this;
  }

   /**
   * Sale price of the gift card
   * @return unitPrice
  **/
  @ApiModelProperty(required = true, value = "Sale price of the gift card")

  public BigDecimal getUnitPrice() {
    return unitPrice;
  }


  public void setUnitPrice(BigDecimal unitPrice) {
    this.unitPrice = unitPrice;
  }


  public InlineResponse2002DataOrderItems totalPrice(BigDecimal totalPrice) {
    
    this.totalPrice = totalPrice;
    return this;
  }

   /**
   * Total order price
   * @return totalPrice
  **/
  @ApiModelProperty(required = true, value = "Total order price")

  public BigDecimal getTotalPrice() {
    return totalPrice;
  }


  public void setTotalPrice(BigDecimal totalPrice) {
    this.totalPrice = totalPrice;
  }


  public InlineResponse2002DataOrderItems quantity(Integer quantity) {
    
    this.quantity = quantity;
    return this;
  }

   /**
   * For self use card, this can be any value between 1 and 10. For a gifting card, it must be 1
   * @return quantity
  **/
  @ApiModelProperty(required = true, value = "For self use card, this can be any value between 1 and 10. For a gifting card, it must be 1")

  public Integer getQuantity() {
    return quantity;
  }


  public void setQuantity(Integer quantity) {
    this.quantity = quantity;
  }


  public InlineResponse2002DataOrderItems isGifting(Boolean isGifting) {
    
    this.isGifting = isGifting;
    return this;
  }

   /**
   * If true its a gifting card, if false it is a self use card
   * @return isGifting
  **/
  @ApiModelProperty(required = true, value = "If true its a gifting card, if false it is a self use card")

  public Boolean getIsGifting() {
    return isGifting;
  }


  public void setIsGifting(Boolean isGifting) {
    this.isGifting = isGifting;
  }


  public InlineResponse2002DataOrderItems mobileNumber(String mobileNumber) {
    
    this.mobileNumber = mobileNumber;
    return this;
  }

   /**
   * Australian mobile number of recipient. Only SMS delivery method is supported for gifting card
   * @return mobileNumber
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Australian mobile number of recipient. Only SMS delivery method is supported for gifting card")

  public String getMobileNumber() {
    return mobileNumber;
  }


  public void setMobileNumber(String mobileNumber) {
    this.mobileNumber = mobileNumber;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    InlineResponse2002DataOrderItems inlineResponse2002DataOrderItems = (InlineResponse2002DataOrderItems) o;
    return Objects.equals(this.designId, inlineResponse2002DataOrderItems.designId) &&
        Objects.equals(this.amount, inlineResponse2002DataOrderItems.amount) &&
        Objects.equals(this.unitPrice, inlineResponse2002DataOrderItems.unitPrice) &&
        Objects.equals(this.totalPrice, inlineResponse2002DataOrderItems.totalPrice) &&
        Objects.equals(this.quantity, inlineResponse2002DataOrderItems.quantity) &&
        Objects.equals(this.isGifting, inlineResponse2002DataOrderItems.isGifting) &&
        Objects.equals(this.mobileNumber, inlineResponse2002DataOrderItems.mobileNumber);
  }

  @Override
  public int hashCode() {
    return Objects.hash(designId, amount, unitPrice, totalPrice, quantity, isGifting, mobileNumber);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class InlineResponse2002DataOrderItems {\n");
    sb.append("    designId: ").append(toIndentedString(designId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    unitPrice: ").append(toIndentedString(unitPrice)).append("\n");
    sb.append("    totalPrice: ").append(toIndentedString(totalPrice)).append("\n");
    sb.append("    quantity: ").append(toIndentedString(quantity)).append("\n");
    sb.append("    isGifting: ").append(toIndentedString(isGifting)).append("\n");
    sb.append("    mobileNumber: ").append(toIndentedString(mobileNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

