/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import au.com.woolworths.village.sdk.openapi.dto.MerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard;
import au.com.woolworths.village.sdk.openapi.dto.MerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * The presence of this object in the response indicates that apple pay is an allowed payment method and instrument in the container for the relevant merchant.
 */
@ApiModel(description = "The presence of this object in the response indicates that apple pay is an allowed payment method and instrument in the container for the relevant merchant.")

public class MerchantProfileResponseAllowedPaymentMethodsApplePay implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CREDIT_CARD = "creditCard";
  @SerializedName(SERIALIZED_NAME_CREDIT_CARD)
  private MerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard creditCard;

  public static final String SERIALIZED_NAME_DEBIT_CARD = "debitCard";
  @SerializedName(SERIALIZED_NAME_DEBIT_CARD)
  private MerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard debitCard;

  /**
   * This property indicates the status of the apple pay service in the container.
   */
  @JsonAdapter(ServiceStatusEnum.Adapter.class)
  public enum ServiceStatusEnum {
    ENABLED("ENABLED"),
    
    DISABLED("DISABLED");

    private String value;

    ServiceStatusEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ServiceStatusEnum fromValue(String value) {
      for (ServiceStatusEnum b : ServiceStatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ServiceStatusEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ServiceStatusEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ServiceStatusEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ServiceStatusEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_SERVICE_STATUS = "serviceStatus";
  @SerializedName(SERIALIZED_NAME_SERVICE_STATUS)
  private ServiceStatusEnum serviceStatus;


  public MerchantProfileResponseAllowedPaymentMethodsApplePay creditCard(MerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard creditCard) {
    
    this.creditCard = creditCard;
    return this;
  }

   /**
   * Get creditCard
   * @return creditCard
  **/
  @ApiModelProperty(required = true, value = "")

  public MerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard getCreditCard() {
    return creditCard;
  }


  public void setCreditCard(MerchantProfileResponseAllowedPaymentMethodsGooglePayCreditCard creditCard) {
    this.creditCard = creditCard;
  }


  public MerchantProfileResponseAllowedPaymentMethodsApplePay debitCard(MerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard debitCard) {
    
    this.debitCard = debitCard;
    return this;
  }

   /**
   * Get debitCard
   * @return debitCard
  **/
  @ApiModelProperty(required = true, value = "")

  public MerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard getDebitCard() {
    return debitCard;
  }


  public void setDebitCard(MerchantProfileResponseAllowedPaymentMethodsGooglePayDebitCard debitCard) {
    this.debitCard = debitCard;
  }


  public MerchantProfileResponseAllowedPaymentMethodsApplePay serviceStatus(ServiceStatusEnum serviceStatus) {
    
    this.serviceStatus = serviceStatus;
    return this;
  }

   /**
   * This property indicates the status of the apple pay service in the container.
   * @return serviceStatus
  **/
  @ApiModelProperty(required = true, value = "This property indicates the status of the apple pay service in the container.")

  public ServiceStatusEnum getServiceStatus() {
    return serviceStatus;
  }


  public void setServiceStatus(ServiceStatusEnum serviceStatus) {
    this.serviceStatus = serviceStatus;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MerchantProfileResponseAllowedPaymentMethodsApplePay merchantProfileResponseAllowedPaymentMethodsApplePay = (MerchantProfileResponseAllowedPaymentMethodsApplePay) o;
    return Objects.equals(this.creditCard, merchantProfileResponseAllowedPaymentMethodsApplePay.creditCard) &&
        Objects.equals(this.debitCard, merchantProfileResponseAllowedPaymentMethodsApplePay.debitCard) &&
        Objects.equals(this.serviceStatus, merchantProfileResponseAllowedPaymentMethodsApplePay.serviceStatus);
  }

  @Override
  public int hashCode() {
    return Objects.hash(creditCard, debitCard, serviceStatus);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MerchantProfileResponseAllowedPaymentMethodsApplePay {\n");
    sb.append("    creditCard: ").append(toIndentedString(creditCard)).append("\n");
    sb.append("    debitCard: ").append(toIndentedString(debitCard)).append("\n");
    sb.append("    serviceStatus: ").append(toIndentedString(serviceStatus)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

