/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import org.threeten.bp.OffsetDateTime;

import java.io.IOException;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Objects;

import au.com.woolworths.village.sdk.model.walletmanagement.PaymentInstrumentStatus;
import io.swagger.annotations.ApiModelProperty;

/**
 * PaymentAgreement
 */

public class PaymentAgreement implements Serializable {
  private static final long serialVersionUID = 1L;

  /**
   * The payment agreement type.
   */
  @JsonAdapter(TypeEnum.Adapter.class)
  public enum TypeEnum {
    RECURRING("RECURRING"),
    
    ADHOC("ADHOC"),
    
    INSTALLMENT("INSTALLMENT");

    private String value;

    TypeEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static TypeEnum fromValue(String value) {
      for (TypeEnum b : TypeEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<TypeEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final TypeEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public TypeEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return TypeEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private TypeEnum type;

  public static final String SERIALIZED_NAME_PAYMENT_INSTRUMENT_ID = "paymentInstrumentId";
  @SerializedName(SERIALIZED_NAME_PAYMENT_INSTRUMENT_ID)
  private String paymentInstrumentId;

  public static final String SERIALIZED_NAME_PAYMENT_INSTRUMENT_TYPE = "paymentInstrumentType";
  @SerializedName(SERIALIZED_NAME_PAYMENT_INSTRUMENT_TYPE)
  private String paymentInstrumentType;

  public static final String SERIALIZED_NAME_SCHEME = "scheme";
  @SerializedName(SERIALIZED_NAME_SCHEME)
  private String scheme;

  public static final String SERIALIZED_NAME_CARD_SUFFIX = "cardSuffix";
  @SerializedName(SERIALIZED_NAME_CARD_SUFFIX)
  private String cardSuffix;

  public static final String SERIALIZED_NAME_EXPIRY_MONTH = "expiryMonth";
  @SerializedName(SERIALIZED_NAME_EXPIRY_MONTH)
  private String expiryMonth;

  public static final String SERIALIZED_NAME_EXPIRY_YEAR = "expiryYear";
  @SerializedName(SERIALIZED_NAME_EXPIRY_YEAR)
  private String expiryYear;

  public static final String SERIALIZED_NAME_START_DATE = "startDate";
  @SerializedName(SERIALIZED_NAME_START_DATE)
  private String startDate;

  public static final String SERIALIZED_NAME_END_DATE = "endDate";
  @SerializedName(SERIALIZED_NAME_END_DATE)
  private String endDate;

  public static final String SERIALIZED_NAME_ALLOWED = "allowed";
  @SerializedName(SERIALIZED_NAME_ALLOWED)
  private Boolean allowed;

  public static final String SERIALIZED_NAME_CHARGE_CYCLE = "chargeCycle";
  @SerializedName(SERIALIZED_NAME_CHARGE_CYCLE)
  private BigDecimal chargeCycle;

  public static final String SERIALIZED_NAME_CREATED_ON = "createdOn";
  @SerializedName(SERIALIZED_NAME_CREATED_ON)
  private String createdOn;

  public static final String SERIALIZED_NAME_DESCRIPTION = "description";
  @SerializedName(SERIALIZED_NAME_DESCRIPTION)
  private String description;

  public static final String SERIALIZED_NAME_EXPIRED = "expired";
  @SerializedName(SERIALIZED_NAME_EXPIRED)
  private Boolean expired;

  public static final String SERIALIZED_NAME_LAST_UPDATED = "lastUpdated";
  @SerializedName(SERIALIZED_NAME_LAST_UPDATED)
  private String lastUpdated;

  public static final String SERIALIZED_NAME_LAST_USED = "lastUsed";
  @SerializedName(SERIALIZED_NAME_LAST_USED)
  private String lastUsed;

  public static final String SERIALIZED_NAME_PAYMENT_TOKEN = "paymentToken";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TOKEN)
  private String paymentToken;

  public static final String SERIALIZED_NAME_PRIMARY = "primary";
  @SerializedName(SERIALIZED_NAME_PRIMARY)
  private Boolean primary;

  public static final String SERIALIZED_NAME_STATUS = "status";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PaymentInstrumentStatus status;

  public static final String SERIALIZED_NAME_PAYMENT_AGREEMENT_STEP_UP = "stepUp";
  @SerializedName(SERIALIZED_NAME_STATUS)
  private PaymentAgreementStepUp stepUp;

  public static final String SERIALIZED_NAME_UPDATE_URL = "updateURL";
  @SerializedName(SERIALIZED_NAME_UPDATE_URL)
  private String updateURL;

  /**
   * The payment agreement charge frequency.
   */
  @JsonAdapter(ChargeFrequencyEnum.Adapter.class)
  public enum ChargeFrequencyEnum {
    WEEKLY("WEEKLY"),
    
    FORTNIGHTLY("FORTNIGHTLY"),
    
    MONTHLY("MONTHLY");

    private String value;

    ChargeFrequencyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ChargeFrequencyEnum fromValue(String value) {
      for (ChargeFrequencyEnum b : ChargeFrequencyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ChargeFrequencyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ChargeFrequencyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ChargeFrequencyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ChargeFrequencyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_CHARGE_FREQUENCY = "chargeFrequency";
  @SerializedName(SERIALIZED_NAME_CHARGE_FREQUENCY)
  private ChargeFrequencyEnum chargeFrequency;

  public static final String SERIALIZED_NAME_CHARGE_AMOUNT = "chargeAmount";
  @SerializedName(SERIALIZED_NAME_CHARGE_AMOUNT)
  private BigDecimal chargeAmount;


  public PaymentAgreement type(TypeEnum type) {
    
    this.type = type;
    return this;
  }

   /**
   * The payment agreement type.
   * @return type
  **/
  @ApiModelProperty(required = true, value = "The payment agreement type.")

  public TypeEnum getType() {
    return type;
  }


  public void setType(TypeEnum type) {
    this.type = type;
  }


  public PaymentAgreement paymentInstrumentId(String paymentInstrumentId) {
    
    this.paymentInstrumentId = paymentInstrumentId;
    return this;
  }

   /**
   * The payment agreement payment instrument id that will be used for the charges.
   * @return paymentInstrumentId
  **/
  @ApiModelProperty(example = "90731", required = true, value = "The payment agreement payment instrument id that will be used for the charges.")

  public String getPaymentInstrumentId() {
    return paymentInstrumentId;
  }


  public void setPaymentInstrumentId(String paymentInstrumentId) {
    this.paymentInstrumentId = paymentInstrumentId;
  }


  public PaymentAgreement paymentInstrumentType(String paymentInstrumentType) {
    
    this.paymentInstrumentType = paymentInstrumentType;
    return this;
  }

   /**
   * The type of the payment instrument used in the payment agreement.
   * @return paymentInstrumentType
  **/
  @ApiModelProperty(example = "CREDIT_CARD", required = true, value = "The type of the payment instrument used in the payment agreement.")

  public String getPaymentInstrumentType() {
    return paymentInstrumentType;
  }


  public void setPaymentInstrumentType(String paymentInstrumentType) {
    this.paymentInstrumentType = paymentInstrumentType;
  }


  public PaymentAgreement scheme(String scheme) {
    
    this.scheme = scheme;
    return this;
  }

   /**
   * The credit card scheme.
   * @return scheme
  **/
  @ApiModelProperty(example = "VISA", required = true, value = "The credit card scheme.")

  public String getScheme() {
    return scheme;
  }


  public void setScheme(String scheme) {
    this.scheme = scheme;
  }


  public PaymentAgreement cardSuffix(String cardSuffix) {
    
    this.cardSuffix = cardSuffix;
    return this;
  }

   /**
   * The suffix (last 4 digits) of the credit card number.
   * @return cardSuffix
  **/
  @ApiModelProperty(example = "4405", required = true, value = "The suffix (last 4 digits) of the credit card number.")

  public String getCardSuffix() {
    return cardSuffix;
  }


  public void setCardSuffix(String cardSuffix) {
    this.cardSuffix = cardSuffix;
  }


  public PaymentAgreement expiryMonth(String expiryMonth) {
    
    this.expiryMonth = expiryMonth;
    return this;
  }

   /**
   * The month of the expiry date of the credit card.
   * @return expiryMonth
  **/
  @ApiModelProperty(example = "11", required = true, value = "The month of the expiry date of the credit card.")

  public String getExpiryMonth() {
    return expiryMonth;
  }


  public void setExpiryMonth(String expiryMonth) {
    this.expiryMonth = expiryMonth;
  }


  public PaymentAgreement expiryYear(String expiryYear) {
    
    this.expiryYear = expiryYear;
    return this;
  }

   /**
   * The year of the expiry date of the credit card.
   * @return expiryYear
  **/
  @ApiModelProperty(example = "22", required = true, value = "The year of the expiry date of the credit card.")

  public String getExpiryYear() {
    return expiryYear;
  }


  public void setExpiryYear(String expiryYear) {
    this.expiryYear = expiryYear;
  }


  public PaymentAgreement startDate(String startDate) {
    
    this.startDate = startDate;
    return this;
  }

   /**
   * The payment agreement start date and time. The timestamp format is ISO8601.
   * @return startDate
  **/
  @ApiModelProperty(example = "2018-09-01T00:00:00.000+1100", required = true, value = "The payment agreement start date and time. The timestamp format is ISO8601.")

  public String getStartDate() {
    return startDate;
  }


  public void setStartDate(String startDate) {
    this.startDate = startDate;
  }


  public PaymentAgreement endDate(String endDate) {
    
    this.endDate = endDate;
    return this;
  }

   /**
   * The payment agreement end date and time. The timestamp format is ISO8601.
   * @return endDate
  **/
  @ApiModelProperty(example = "2018-12-31T23:59:59.999+1100", required = true, value = "The payment agreement end date and time. The timestamp format is ISO8601.")

  public String getEndDate() {
    return endDate;
  }


  public void setEndDate(String endDate) {
    this.endDate = endDate;
  }


  public PaymentAgreement chargeFrequency(ChargeFrequencyEnum chargeFrequency) {
    
    this.chargeFrequency = chargeFrequency;
    return this;
  }

   /**
   * The payment agreement charge frequency.
   * @return chargeFrequency
  **/
  @ApiModelProperty(required = true, value = "The payment agreement charge frequency.")

  public ChargeFrequencyEnum getChargeFrequency() {
    return chargeFrequency;
  }


  public void setChargeFrequency(ChargeFrequencyEnum chargeFrequency) {
    this.chargeFrequency = chargeFrequency;
  }


  public PaymentAgreement chargeAmount(BigDecimal chargeAmount) {

    this.chargeAmount = chargeAmount;
    return this;
  }

   /**
   * The amount that will be charged at the frequency specified in the payment agreement.
   * @return chargeAmount
  **/
  @ApiModelProperty(example = "25.99", required = true, value = "The amount that will be charged at the frequency specified in the payment agreement.")

  public BigDecimal getChargeAmount() {
    return chargeAmount;
  }


  public void setChargeAmount(BigDecimal chargeAmount) {
    this.chargeAmount = chargeAmount;
  }

  public PaymentAgreement allowed(Boolean allowed) {

    this.allowed = allowed;
    return this;
  }

  /**
   * A flag to indicate if the merchant profile in the container allows the use of this payment agreement.
   * @return allowed
   **/
  @ApiModelProperty(example = "true", required = false, value = "A flag to indicate if the merchant profile in the container allows the use of this payment agreement.")

  public Boolean getAllowed() {
    return allowed;
  }


  public void setAllowed(Boolean allowed) {
    this.allowed = allowed;
  }

  public PaymentAgreement chargeCycle(Boolean allowed) {

    this.chargeCycle = chargeCycle;
    return this;
  }

  /**
   *
   * @return chargeCycle
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public BigDecimal getChargeCycle() {
    return chargeCycle;
  }


  public void setChargeCycle(BigDecimal chargeCycle) {
    this.chargeCycle = chargeCycle;
  }


  public PaymentAgreement createdOn(String createdOn) {

    this.createdOn = createdOn;
    return this;
  }

  /**
   *
   * @return createdOn
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public String getCreatedOn() {
    return createdOn;
  }


  public void setCreatedOn(String createdOn) {
    this.createdOn = createdOn;
  }

  public PaymentAgreement description(String description) {

    this.description = description;
    return this;
  }

  /**
   *
   * @return description
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public String getDescription() {
    return description;
  }


  public void setDescription(String description) {
    this.description = description;
  }


  public PaymentAgreement expired(Boolean expired) {

    this.expired = expired;
    return this;
  }

  /**
   *
   * @return expired
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public Boolean getExpired() {
    return expired;
  }


  public void setExpired(Boolean expired) {
    this.expired = expired;
  }


  public PaymentAgreement lastUpdated(String lastUpdated) {

    this.lastUpdated = lastUpdated;
    return this;
  }

  /**
   *
   * @return lastUpdated
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public String getLastUpdated() {
    return lastUpdated;
  }


  public void setLastUpdated(String lastUpdated) {
    this.lastUpdated = lastUpdated;
  }

  public PaymentAgreement lastUsed(String lastUsed) {

    this.lastUsed = lastUsed;
    return this;
  }

  /**
   *
   * @return lastUsed
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public String getLastUsed() {
    return lastUsed;
  }


  public void setLastUsed(String lastUsed) {
    this.lastUsed = lastUsed;
  }

  public PaymentAgreement status(PaymentInstrumentStatus status) {

    this.status = status;
    return this;
  }

  /**
   *
   * @return status
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public PaymentInstrumentStatus getStatus() {
    return status;
  }


  public void setStatus(PaymentInstrumentStatus status) {
    this.status = status;
  }

  public PaymentAgreement stepUp(PaymentAgreementStepUp stepUp) {

    this.stepUp = stepUp;
    return this;
  }

  /**
   *
   * @return stepUp
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public PaymentAgreementStepUp getStepUp() {
    return stepUp;
  }


  public void setStepUp(PaymentAgreementStepUp stepUp) {
    this.stepUp = stepUp;
  }

  public PaymentAgreement updateURL(String updateURL) {

    this.updateURL = updateURL;
    return this;
  }

  /**
   *
   * @return updateURL
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public String getUpdateURL() {
    return updateURL;
  }


  public void setUpdateURL(String updateURL) {
    this.updateURL = updateURL;
  }


  public PaymentAgreement paymentToken(String paymentToken) {

    this.paymentToken = paymentToken;
    return this;
  }

  /**
   *
   * @return paymentToken
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public String getPaymentToken() {
    return paymentToken;
  }


  public void setPaymentToken(String paymentToken) {
    this.paymentToken = paymentToken;
  }


  public PaymentAgreement primary(Boolean primary) {

    this.primary = primary;
    return this;
  }

  /**
   *
   * @return primary
   **/
  @ApiModelProperty(example = "true", required = false, value = "")

  public Boolean getPrimary() {
    return primary;
  }


  public void setPrimary(Boolean primary) {
    this.primary = primary;
  }

  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAgreement paymentAgreement = (PaymentAgreement) o;
    return Objects.equals(this.type, paymentAgreement.type) &&
        Objects.equals(this.paymentInstrumentId, paymentAgreement.paymentInstrumentId) &&
        Objects.equals(this.paymentInstrumentType, paymentAgreement.paymentInstrumentType) &&
        Objects.equals(this.scheme, paymentAgreement.scheme) &&
        Objects.equals(this.cardSuffix, paymentAgreement.cardSuffix) &&
        Objects.equals(this.expiryMonth, paymentAgreement.expiryMonth) &&
        Objects.equals(this.expiryYear, paymentAgreement.expiryYear) &&
        Objects.equals(this.startDate, paymentAgreement.startDate) &&
        Objects.equals(this.endDate, paymentAgreement.endDate) &&
        Objects.equals(this.chargeFrequency, paymentAgreement.chargeFrequency) &&
        Objects.equals(this.chargeAmount, paymentAgreement.chargeAmount) &&
        Objects.equals(this.allowed, paymentAgreement.allowed) &&
        Objects.equals(this.chargeCycle, paymentAgreement.chargeCycle) &&
        Objects.equals(this.createdOn, paymentAgreement.createdOn) &&
        Objects.equals(this.description, paymentAgreement.description) &&
        Objects.equals(this.expired, paymentAgreement.expired) &&
        Objects.equals(this.expired, paymentAgreement.lastUpdated) &&
        Objects.equals(this.lastUsed, paymentAgreement.lastUsed) &&
        Objects.equals(this.paymentToken, paymentAgreement.paymentToken) &&
        Objects.equals(this.primary, paymentAgreement.primary);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, paymentInstrumentId, paymentInstrumentType, scheme, cardSuffix, expiryMonth, expiryYear, startDate, endDate, chargeFrequency, chargeAmount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAgreement {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    paymentInstrumentId: ").append(toIndentedString(paymentInstrumentId)).append("\n");
    sb.append("    paymentInstrumentType: ").append(toIndentedString(paymentInstrumentType)).append("\n");
    sb.append("    scheme: ").append(toIndentedString(scheme)).append("\n");
    sb.append("    cardSuffix: ").append(toIndentedString(cardSuffix)).append("\n");
    sb.append("    expiryMonth: ").append(toIndentedString(expiryMonth)).append("\n");
    sb.append("    expiryYear: ").append(toIndentedString(expiryYear)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    chargeFrequency: ").append(toIndentedString(chargeFrequency)).append("\n");
    sb.append("    chargeAmount: ").append(toIndentedString(chargeAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

