/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import java.util.Objects;
import java.util.Arrays;
import au.com.woolworths.village.sdk.openapi.dto.CreatePaymentAgreementRequestBillingAddress;
import au.com.woolworths.village.sdk.openapi.dto.CreatePaymentAgreementRequestShippingAddress;
import au.com.woolworths.village.sdk.openapi.dto.UpdatePaymentAgreementRequestFraudPayload;
import au.com.woolworths.village.sdk.openapi.dto.UpdatePaymentAgreementRequestPaymentAgreement;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.io.Serializable;

/**
 * The JSON request structure of the Update Payment Agreement endpoint.
 */
@ApiModel(description = "The JSON request structure of the Update Payment Agreement endpoint.")

public class UpdatePaymentAgreementRequest implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_CLIENT_REFERENCE = "clientReference";
  @SerializedName(SERIALIZED_NAME_CLIENT_REFERENCE)
  private String clientReference;

  public static final String SERIALIZED_NAME_CUSTOMER_REF = "customerRef";
  @SerializedName(SERIALIZED_NAME_CUSTOMER_REF)
  private String customerRef;

  public static final String SERIALIZED_NAME_BILLING_ADDRESS = "billingAddress";
  @SerializedName(SERIALIZED_NAME_BILLING_ADDRESS)
  private CreatePaymentAgreementRequestBillingAddress billingAddress;

  public static final String SERIALIZED_NAME_SHIPPING_ADDRESS = "shippingAddress";
  @SerializedName(SERIALIZED_NAME_SHIPPING_ADDRESS)
  private CreatePaymentAgreementRequestShippingAddress shippingAddress;

  public static final String SERIALIZED_NAME_PAYMENT_AGREEMENT = "paymentAgreement";
  @SerializedName(SERIALIZED_NAME_PAYMENT_AGREEMENT)
  private UpdatePaymentAgreementRequestPaymentAgreement paymentAgreement;

  public static final String SERIALIZED_NAME_FRAUD_PAYLOAD = "fraudPayload";
  @SerializedName(SERIALIZED_NAME_FRAUD_PAYLOAD)
  private UpdatePaymentAgreementRequestFraudPayload fraudPayload;


  public UpdatePaymentAgreementRequest clientReference(String clientReference) {
    
    this.clientReference = clientReference;
    return this;
  }

   /**
   * A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system.
   * @return clientReference
  **/
  @ApiModelProperty(example = "T5ESYRPWJKPHF54", required = true, value = "A merchant application specific reference number. This number should uniquely identify the transaction in the merchant’s system.")

  public String getClientReference() {
    return clientReference;
  }


  public void setClientReference(String clientReference) {
    this.clientReference = clientReference;
  }


  public UpdatePaymentAgreementRequest customerRef(String customerRef) {
    
    this.customerRef = customerRef;
    return this;
  }

   /**
   * A merchant application specific reference number. This number should uniquely identify the customer in the merchant’s system.
   * @return customerRef
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "654321", value = "A merchant application specific reference number. This number should uniquely identify the customer in the merchant’s system.")

  public String getCustomerRef() {
    return customerRef;
  }


  public void setCustomerRef(String customerRef) {
    this.customerRef = customerRef;
  }


  public UpdatePaymentAgreementRequest billingAddress(CreatePaymentAgreementRequestBillingAddress billingAddress) {
    
    this.billingAddress = billingAddress;
    return this;
  }

   /**
   * Get billingAddress
   * @return billingAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreatePaymentAgreementRequestBillingAddress getBillingAddress() {
    return billingAddress;
  }


  public void setBillingAddress(CreatePaymentAgreementRequestBillingAddress billingAddress) {
    this.billingAddress = billingAddress;
  }


  public UpdatePaymentAgreementRequest shippingAddress(CreatePaymentAgreementRequestShippingAddress shippingAddress) {
    
    this.shippingAddress = shippingAddress;
    return this;
  }

   /**
   * Get shippingAddress
   * @return shippingAddress
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public CreatePaymentAgreementRequestShippingAddress getShippingAddress() {
    return shippingAddress;
  }


  public void setShippingAddress(CreatePaymentAgreementRequestShippingAddress shippingAddress) {
    this.shippingAddress = shippingAddress;
  }


  public UpdatePaymentAgreementRequest paymentAgreement(UpdatePaymentAgreementRequestPaymentAgreement paymentAgreement) {
    
    this.paymentAgreement = paymentAgreement;
    return this;
  }

   /**
   * Get paymentAgreement
   * @return paymentAgreement
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UpdatePaymentAgreementRequestPaymentAgreement getPaymentAgreement() {
    return paymentAgreement;
  }


  public void setPaymentAgreement(UpdatePaymentAgreementRequestPaymentAgreement paymentAgreement) {
    this.paymentAgreement = paymentAgreement;
  }


  public UpdatePaymentAgreementRequest fraudPayload(UpdatePaymentAgreementRequestFraudPayload fraudPayload) {
    
    this.fraudPayload = fraudPayload;
    return this;
  }

   /**
   * Get fraudPayload
   * @return fraudPayload
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public UpdatePaymentAgreementRequestFraudPayload getFraudPayload() {
    return fraudPayload;
  }


  public void setFraudPayload(UpdatePaymentAgreementRequestFraudPayload fraudPayload) {
    this.fraudPayload = fraudPayload;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    UpdatePaymentAgreementRequest updatePaymentAgreementRequest = (UpdatePaymentAgreementRequest) o;
    return Objects.equals(this.clientReference, updatePaymentAgreementRequest.clientReference) &&
        Objects.equals(this.customerRef, updatePaymentAgreementRequest.customerRef) &&
        Objects.equals(this.billingAddress, updatePaymentAgreementRequest.billingAddress) &&
        Objects.equals(this.shippingAddress, updatePaymentAgreementRequest.shippingAddress) &&
        Objects.equals(this.paymentAgreement, updatePaymentAgreementRequest.paymentAgreement) &&
        Objects.equals(this.fraudPayload, updatePaymentAgreementRequest.fraudPayload);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clientReference, customerRef, billingAddress, shippingAddress, paymentAgreement, fraudPayload);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class UpdatePaymentAgreementRequest {\n");
    sb.append("    clientReference: ").append(toIndentedString(clientReference)).append("\n");
    sb.append("    customerRef: ").append(toIndentedString(customerRef)).append("\n");
    sb.append("    billingAddress: ").append(toIndentedString(billingAddress)).append("\n");
    sb.append("    shippingAddress: ").append(toIndentedString(shippingAddress)).append("\n");
    sb.append("    paymentAgreement: ").append(toIndentedString(paymentAgreement)).append("\n");
    sb.append("    fraudPayload: ").append(toIndentedString(fraudPayload)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

