/*
 * Wpay APIs
 * Wpay APIs for payments and gifting
 *
 * The version of the OpenAPI document: 1.0.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package au.com.woolworths.village.sdk.openapi.dto;

import com.google.gson.annotations.SerializedName;

import java.io.Serializable;
import java.util.Objects;

import io.swagger.annotations.ApiModelProperty;

/**
 * VerifyPaymentInstrumentsSuccessResponseVerifyResponses
 */

public class VerifyPaymentInstrumentsSuccessResponseVerifyResponses implements Serializable {
  private static final long serialVersionUID = 1L;

  public static final String SERIALIZED_NAME_PAYMENT_TOKEN = "paymentToken";
  @SerializedName(SERIALIZED_NAME_PAYMENT_TOKEN)
  private String paymentToken;

  public static final String SERIALIZED_NAME_VERIFY_TRANSACTION_REF = "verifyTransactionRef";
  @SerializedName(SERIALIZED_NAME_VERIFY_TRANSACTION_REF)
  private String verifyTransactionRef;

  public static final String SERIALIZED_NAME_EXTERNAL_SERVICE_CODE = "externalServiceCode";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SERVICE_CODE)
  private String externalServiceCode;

  public static final String SERIALIZED_NAME_EXTERNAL_SERVICE_MESSAGE = "externalServiceMessage";
  @SerializedName(SERIALIZED_NAME_EXTERNAL_SERVICE_MESSAGE)
  private String externalServiceMessage;


  public VerifyPaymentInstrumentsSuccessResponseVerifyResponses paymentToken(String paymentToken) {
    
    this.paymentToken = paymentToken;
    return this;
  }

   /**
   * The payment token.
   * @return paymentToken
  **/
  @ApiModelProperty(example = "f63fbfa8-0a2f-48a6-9162-6b102161a05b", required = true, value = "The payment token.")

  public String getPaymentToken() {
    return paymentToken;
  }


  public void setPaymentToken(String paymentToken) {
    this.paymentToken = paymentToken;
  }


  public VerifyPaymentInstrumentsSuccessResponseVerifyResponses verifyTransactionRef(String verifyTransactionRef) {
    
    this.verifyTransactionRef = verifyTransactionRef;
    return this;
  }

   /**
   * Container reference in the transaction logs. This number uniquely identifies the transaction in the container.
   * @return verifyTransactionRef
  **/
  @ApiModelProperty(example = "1000000009303281", required = true, value = "Container reference in the transaction logs. This number uniquely identifies the transaction in the container.")

  public String getVerifyTransactionRef() {
    return verifyTransactionRef;
  }


  public void setVerifyTransactionRef(String verifyTransactionRef) {
    this.verifyTransactionRef = verifyTransactionRef;
  }


  public VerifyPaymentInstrumentsSuccessResponseVerifyResponses externalServiceCode(String externalServiceCode) {
    
    this.externalServiceCode = externalServiceCode;
    return this;
  }

   /**
   * The external service code (from eg. Webpay). This property is only included in the response if it is enabled in the consumers API configuration.
   * @return externalServiceCode
  **/
  @ApiModelProperty(example = "00", required = true, value = "The external service code (from eg. Webpay). This property is only included in the response if it is enabled in the consumers API configuration.")

  public String getExternalServiceCode() {
    return externalServiceCode;
  }


  public void setExternalServiceCode(String externalServiceCode) {
    this.externalServiceCode = externalServiceCode;
  }


  public VerifyPaymentInstrumentsSuccessResponseVerifyResponses externalServiceMessage(String externalServiceMessage) {
    
    this.externalServiceMessage = externalServiceMessage;
    return this;
  }

   /**
   * The external service message (from eg. Webpay). This property is only included in the response if it is enabled in the consumers API configuration.
   * @return externalServiceMessage
  **/
  @ApiModelProperty(example = "ACCEPTED", required = true, value = "The external service message (from eg. Webpay). This property is only included in the response if it is enabled in the consumers API configuration.")

  public String getExternalServiceMessage() {
    return externalServiceMessage;
  }


  public void setExternalServiceMessage(String externalServiceMessage) {
    this.externalServiceMessage = externalServiceMessage;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VerifyPaymentInstrumentsSuccessResponseVerifyResponses verifyPaymentInstrumentsSuccessResponseVerifyResponses = (VerifyPaymentInstrumentsSuccessResponseVerifyResponses) o;
    return Objects.equals(this.paymentToken, verifyPaymentInstrumentsSuccessResponseVerifyResponses.paymentToken) &&
        Objects.equals(this.verifyTransactionRef, verifyPaymentInstrumentsSuccessResponseVerifyResponses.verifyTransactionRef) &&
        Objects.equals(this.externalServiceCode, verifyPaymentInstrumentsSuccessResponseVerifyResponses.externalServiceCode) &&
        Objects.equals(this.externalServiceMessage, verifyPaymentInstrumentsSuccessResponseVerifyResponses.externalServiceMessage);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentToken, verifyTransactionRef, externalServiceCode, externalServiceMessage);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VerifyPaymentInstrumentsSuccessResponseVerifyResponses {\n");
    sb.append("    paymentToken: ").append(toIndentedString(paymentToken)).append("\n");
    sb.append("    verifyTransactionRef: ").append(toIndentedString(verifyTransactionRef)).append("\n");
    sb.append("    externalServiceCode: ").append(toIndentedString(externalServiceCode)).append("\n");
    sb.append("    externalServiceMessage: ").append(toIndentedString(externalServiceMessage)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

