version: 2.1

orbs:
 android: circleci/android@0.2.1

common_config: &config
  executor: android/android
  working_directory: ~/repository

persist: &persist
  root: ~/
  paths:
    - repository

jobs:
  unit_tests:
      <<: *config

      steps:
        - checkout
        - run:
            # This is just linting for now, we will need to add the unit tests too
            command: ./gradlew lint
        - persist_to_workspace: *persist

  build:
    <<: *config

    steps:
      - attach_workspace:
          # must be absolute path or relative path from working_directory
          at: ~/
      - run:
          command: ./gradlew assembleRelease
      - store_artifacts:
          path: lib/build/outputs/aar
      - persist_to_workspace: *persist

workflows:
  build_and_publish:
    jobs:
      - unit_tests
      - build:
          requires:
            - unit_tests
      - hold:
          filters:
            branches:
              only:
                - /release.*/
                - master
          requires:
            - build
          type: approval
