name: 'Build'

on:
  push:
    branches: [ master ]

  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set git config
        run: |
           git config user.name github-actions
           git config user.email github-actions@github.com

      - name: Setup Java 8
        uses: actions/setup-java@v1
        with:
          java-version: 8

      - name: Build
        uses: burrunan/gradle-cache-action@v1
        with:
          arguments: clean lint assembleRelease

      - name: Tag
        if: ${{ github.ref == 'refs/heads/master' }}
        run: ./scripts/tag.sh
        env:
          GH_AUTH_TOKEN: ${{ secrets.GH_AUTH_TOKEN }}

      - name: Push changes
        if: ${{ github.ref == 'refs/heads/master' }}
        run: |
          git push
          git push --tags